### PR TITLE
Improve password generation and validation routine #34

### PR DESCRIPTION
**Pull request by ashklianko**
-Using nanoid lib to generate strong password
-Using owasp-password-strength-test lib to verify password strength, that takes into account passphrases. Most common passwords will be not accepted as strong
-Not letting create weak passwords, only those that considered strong
-Showing circles with hints under password to inform what to fix with a new password

### CODE REVIEW

**Review by alansemenov — CHANGES_REQUESTED** [review]
1. We need to change wording of the password strength grades. Having "_good_" as the top strength can be confusing since there's always something better than good.

So I suggest the following

GOOD = 'very strong',
ALMOST_GOOD = 'strong',
NOT_GOOD = 'medium',
BAD = 'weak',
VERY_BAD = 'very weak'

The last two should not be acceptable, it has to be at least "medium".

2. There's a Codacy error: https://app.codacy.com/manual/enonic/app-users/pullRequest?prid=6894757

**Comment by ashklianko** [comment]
Updated

**Review by alansemenov — CHANGES_REQUESTED** [review]
1. We should change around the strength visualisation logic (let me know if it's possible with the OWASP lib we're using). As of now it's very confusing that the stronger the password gets the less visual elements you see (takes a while to realise that each element represents a missing requirement).
It should be like this:
* No visualisation initially
* 1 element for "Very weak"
* 2 elements for "Weak"
* and so on until 5 elements for "Very strong" (see screenshots at the bottom)

2. Change the colored elements from circles to "bricks" 7px high and 15px wide

3. Add a helptext under the Show/Generate links saying "_The password must be at least 10 characters long and either contain at least one uppercase/special character or be a passphrase_"

4. Remove tooltips from the colored elements (the help text should solve this)

5. Change the colors as follows:
* Very weak - `red`
* Weak - `brown`
* Medium - `@admin-orange`
* Strong - `#92a682`
* Very strong - `@admin-green`

6. Change the texts to upper case

Screenshot 2021-02-04 at 16 44 00

Screenshot 2021-02-04 at 16 44 30

Screenshot 2021-02-04 at 16 25 53

Screenshot 2021-02-04 at 16 30 12

Screenshot 2021-02-04 at 16 31 09

**Comment by ashklianko** [comment]
Updated

**Review by alansemenov — APPROVED** [review]
Great stuff

**Pull request merged**
