### PR TITLE
Added accessibility navigation to 'Create New' dialog items (#649)

### PR DESCRIPTION
**Pull request by reisfmb**

### CODE REVIEW

**Review by ashklianko — CHANGES_REQUESTED** [review]
After I press enter on any item with children and it gets expanded then after that tabbing stops working at all. 
In general when working with slickgrid it is not trivial task to add tabbing on certain elements because
a) Slickgrid is redrawing elements when it wants to and when you're not expecting this
b) Slickgrid items are not ordered properly in dom tree because of absolute positioning, so tabbing might jump from the first element to the last one

**Comment by alansemenov** [comment]
I also think that setting `tabIndex` should be done by the Grid class itself. It definitely won't hurt if Grid's row elements will _always_ have `tabIndex`, rather than doing a hacky-style fix for every class that is using SlickGrid.

**Comment by ashklianko** [comment]
> I also think that setting `tabIndex` should be done by the Grid class itself. It definitely won't hurt if Grid's row elements will _always_ have `tabIndex`, rather than doing a hacky-style fix for every class that is using SlickGrid.

But still, ordering will remain as an issue

**Comment by ashklianko** [comment]
I'll assign task to myself @reisfmb

**Comment by reisfmb** [comment]
> I also think that setting `tabIndex` should be done by the Grid class itself. It definitely won't hurt if Grid's row elements will _always_ have `tabIndex`, rather than doing a hacky-style fix for every class that is using SlickGrid.

I initially tried that, but tabindex will only highlight the items... There's the need to also add Enter event listener to trigger the click. Since idk if that would after other parts of the system using the Grid, I tried to isolate that case exposing the slickgrid, and only adding tabindex + enter event to the case reported in the issue

**Pull request closed without merging**
